# Generated by Django 4.2.3 on 2023-08-06 10:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Услуга')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='quality',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Вид услуги')),
                ('max_price', models.IntegerField(verbose_name='Минимальная цена')),
                ('min_price', models.IntegerField(verbose_name='Максимальная цена')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
