# Generated by Django 4.2.3 on 2023-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_alter_feedback_quality_servicecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='min_price',
            field=models.IntegerField(null=True, verbose_name='Максимальная цена'),
        ),
    ]
