# Generated by Django 4.2.3 on 2023-08-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_servicecategory_min_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='max_price',
            field=models.IntegerField(null=True, verbose_name='Максимальная цена'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='min_price',
            field=models.IntegerField(default=1, verbose_name='Минимальная цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Вид услуги'),
        ),
    ]
