# Generated by Django 4.2.3 on 2023-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_servicecategory_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='max_price',
            field=models.IntegerField(default=None, null=True, verbose_name='Максимальная цена'),
        ),
    ]
