# Generated by Django 4.2.3 on 2023-08-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_servicecategory_max_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Вид услуги'),
        ),
    ]
