# Generated by Django 4.2.3 on 2023-08-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_servicecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Вид услуги'),
        ),
    ]
